function calculateInterest (deposit, regContribution, contributeFreq, interestRate, compoundFreq) {
    /**
     *  deposit: Int -> The initial deposit for the interest calculation.
     *  regContribution: Int -> the amount of regular contribution.
     *  contributeFreq: Int -> the frequency of contribution. 1 -> yearly, 12 -> monthly, 26 -> fortnightly, 
     *      52 -> weekly, 365 -> daily. 
     *  interestRate: Float -> the compound interest Rate (annual rate).
     *  compoundFreq: Int -> the frequency of compounding the interest. 1 -> yearly, 12 -> monthly.
     *  Returns: the amount of interest generated in a year, by the given parameters. 
     * 
     *  Assuming contribution happens on the end of each cycle. 
     */

}


function depositInterest (deposit, interestRate, compoundFreq) {
    /**
     *  Calculate the interest generated by the deposit.
     */ 
    
}